import { NextResponse } from "next/server"
import type { JobOpportunity, FitAnalysis, CoverLetterDraft } from "@/lib/types"

export async function POST(request: Request) {
  try {
    const { job, analysis, coverLetter } = (await request.json()) as {
      job: JobOpportunity
      analysis?: FitAnalysis
      coverLetter?: CoverLetterDraft
    }

    // Generate markdown content
    let markdown = `# ${job.title} at ${job.company}\n\n`

    markdown += `## Job Details\n\n`
    markdown += `- **Location**: ${job.location}\n`
    markdown += `- **Remote Status**: ${job.remoteStatus}\n`
    markdown += `- **Source**: ${job.source}\n`
    if (job.salaryRange) {
      markdown += `- **Salary Range**: ${job.salaryRange}\n`
    }
    markdown += `- **Application URL**: ${job.applicationUrl}\n\n`

    if (analysis) {
      markdown += `## Fit Analysis\n\n`
      markdown += `**Overall Score**: ${analysis.overallScore}%\n\n`
      markdown += `### Strengths\n\n`
      analysis.strengths.forEach((s) => {
        markdown += `- ${s}\n`
      })
      markdown += `\n`

      if (analysis.concerns.length > 0) {
        markdown += `### Concerns\n\n`
        analysis.concerns.forEach((c) => {
          markdown += `- ${c}\n`
        })
        markdown += `\n`
      }
    }

    markdown += `## Job Description\n\n`
    markdown += `${job.description}\n\n`

    if (job.requirements.length > 0) {
      markdown += `## Requirements\n\n`
      job.requirements.forEach((r) => {
        markdown += `- ${r}\n`
      })
      markdown += `\n`
    }

    if (job.techStack.length > 0) {
      markdown += `## Tech Stack\n\n`
      markdown += job.techStack.join(", ") + "\n\n"
    }

    if (coverLetter) {
      markdown += `## Cover Letter\n\n`
      markdown += `${coverLetter.content}\n\n`
    }

    markdown += `---\n\n`
    markdown += `*Generated by Scouter - AI-Powered Job Search Assistant*\n`

    return NextResponse.json({ markdown })
  } catch (error) {
    console.error("[v0] Error exporting markdown:", error)
    return NextResponse.json({ error: "Failed to export markdown" }, { status: 500 })
  }
}
